fsck: fix compilation on musl based systems (loff_t)
exfatprogs 1.2.7 (and current git master) doesn't build on a musl/llvm
based gentoo. fsck/fsck.c compilation fails with the following message:

make[2]: Entering directory '/home/geoffrey/Sources/gentoo/exfatprogs/build/fsck'
  CC       fsck.o
../../fsck/fsck.c:1086:46: error: unknown type name 'loff_t'; did you mean 'off_t'?
 1086 |                 struct exfat_dentry *dentry, loff_t dentry_off)
      |                                              ^~~~~~
      |                                              off_t
../../fsck/fsck.c: In function 'read_upcase_table':
../../fsck/fsck.c:1178:9: error: unknown type name 'loff_t'; did you mean 'off_t'?
 1178 |         loff_t dentry_off;
      |         ^~~~~~
      |         off_t
../../fsck/fsck.c:1253:26: warning: implicit declaration of function 'exfat_repair_upcase_table'; did you mean 'exfat_repair_rename_ask'? [-Wimplicit-function-declaration]
 1253 |                 retval = exfat_repair_upcase_table(exfat, dentry, dentry_off);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                          exfat_repair_rename_ask
../../fsck/fsck.c: At top level:
../../fsck/fsck.c:1048:13: warning: 'exfat_has_default_upcase_table' defined but not used [-Wunused-function]
 1048 | static bool exfat_has_default_upcase_table(struct exfat *exfat, clus_t *clu)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:400: fsck.o] Error 1
make[2]: Leaving directory '/home/geoffrey/Sources/gentoo/exfatprogs/build/fsck'
make[1]: *** [Makefile:505: all-recursive] Error 1
make[1]: Leaving directory '/home/geoffrey/Sources/gentoo/exfatprogs/build'
make: *** [Makefile:396: all] Error 2

After a (quick) glance at the code, it seems to be a typo as off_t is used
everywhere, including in struct exfat_lookup_filter definition.

Signed-off-by: Geoffrey Brun <geoffrey+git@spekadyon.org>
Reviewed-by: Hyunchul Lee <hyc.lee@gmail.com>
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>